### ISSUE TITLE
Slapper don`t save

### ISSUE THREAD

**Issue by samp-pinch** [jojoe77777/SlapperCache#1]
I have Slapper, SlapperRotation and SlapperCache
But SlapperCache doesn't save Slappers, and when server stopped, they disappear ...but the files still exist O.o
Jojoe pls do not close without explaining...

**Comment by jojoe77777** [comment]
To trigger the uncaching you have to delete the "slappers_restored_file" file

**Comment by inxomnyaa** [comment]
General question: whats this for, and should i use it?

**Comment by jojoe77777** [comment]
@thebigsmileXD generally for if you have multiple servers that should have the same slappers.

**Comment by inxomnyaa** [comment]
I see. Another question: my Slappers disappear randomly, and on /et nuke others (GrabBag feature). I made sure that the command isn't called in TimeCommander, still, the Slapper will disappear.
