### ISSUE TITLE
Slapper cache not restoring commands

### ISSUE THREAD

**Issue by Sandertv** [jojoe77777/SlapperCache#3]
Hello! So recently all my Slappers decided to vanish again, most likely due to another entity related plugin, and I tested out SlapperCache. It did restore my slappers correctly, but for some reason the commands did not come with them. Is this a plugin bug? Or just not implemented? I hope you can fix it!

**Comment by jojoe77777** [comment]
It caches NBT, which should include commands...

**Comment by Sandertv** [comment]
I think this can be closed. It's most likely due to the plugin caching Slappers when they are being created, and there are no commands on the moment of creating it.
